Resources/Prototypes/ADT/Drones/Drone-Engineer/Entities/Mobs/Player/engineeringdrone.yml, Resources/Prototypes/ADT/Drones/Drone-Medical/Entities/Mobs/Player/medicaldrone.yml, Resources/Prototypes/ADT/Drones/Drone-Service/Entities/Mobs/Player/servicedrone.yml
**Медиа**
**Проверки**
**Изменения**
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!
=> Исправлены Дроны (облачка, писк ПИИ, летают)

Resources/Prototypes/ADT/Customization/Markings/head.yml, Resources/Prototypes/ADT/Customization/Markings/tale.yml
По просьбе заказчика - Суккубус теперь Tail, Рога теперь HeadTop. 
Проверьте что Рога и хвост "Суккубус" доступен спонсорке, плз
=> Суккубус теперь Tail, Рога теперь HeadTop

Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/orientalears.yml
=> loadout fixed

Resources/Prototypes/ADT/Drones/Drone-Engineer/Entities/Mobs/Player/engineeringdrone.yml, Resources/Prototypes/ADT/Drones/Drone-Medical/Entities/Mobs/Player/medicaldrone.yml, Resources/Prototypes/ADT/Drones/Drone-Service/Entities/Mobs/Player/servicedrone.yml, Resources/Prototypes/ADT/KD/Channels/RoboticChannel.yml, Resources/Prototypes/Entities/Mobs/Player/silicon.yml
дроны могут общаться между собой.
Не добавил ключа к этому каналу, ТК дроны обмениваются специальными волнами. Человек просто не поймет. Тут надо специальную гарнитуру делать(что будет бесполезно)
=> Добавил новый канал "роботический"

Content.Client/UserInterface/Systems/Chat/ChatUIController.cs, Content.Shared/Administration/AdminFlags.cs, Resources/clientCommandPerms.yml, Resources/engineCommandPerms.yml
Добавлена отдельная роль админа для админчата
=> Added adminChat in admin flags

Content.Server/ADT/Lizard/LizardBloodComponent.cs, Content.Server/ADT/Lizard/LizardBloodSystem.cs, Resources/Locale/ru-RU/ADT/Reagents/adt_medicine.ftl, Resources/Prototypes/ADT/Reagents/medicine.yml, Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
=> Lizard properties

Resources/Prototypes/Entities/Mobs/NPCs/revenant.yml, Resources/Prototypes/Entities/Objects/Fun/pai.yml, Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml, Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml, Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml, Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
Убрана возможность игры за кадета после некоторого времени
=> Fix time for srtarting professions

Resources/Prototypes/Catalog/VendingMachines/Inventories/janidrobe.yml
Ужас, галоши спавнятся только на самом уборщике при выборе профы ! Исправляем
=> Добавляет галоши в автомат уборщика

Resources/Maps/ADT/Shuttles/Helios_chariot.yml, Resources/Maps/ADT/Shuttles/Jastreb_Spirit_Of_The_Steppe.yml, Resources/Maps/ADT/Shuttles/LSS36Mk2.yml, Resources/Maps/ADT/Shuttles/Silver_chariot.yml
Добавлено 4 шаттла для ивентов
=> Added four new shuttles

Resources/Prototypes/Entities/Clothing/Eyes/hud.yml
Подготовка ямл к добавлению компонентов HUD
=> Prepare to huds add

Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml, Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml, Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml
Теперь у HoS (ГСБ) в рюкзаке спавниться BoxSurvivalSecurity как у всех СБшников (было BoxSurvival)
=> Исправлен BoxSurvivalSecurity у HOS

Resources/Textures/ADT/Clothing/Neck/Chokers/сhoker_spike.rsi/meta.json
**Медиа**
**Проверки**
**Изменения**
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!
=> fix 1 symbol ''c'' >> "c"

Resources/Prototypes/Catalog/Research/technologies.yml, Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Икс, прости за постоянное дергание новыми коммитами :D
=> Опять доделываю то, что сделал не правильно

Resources/Prototypes/ADT/Entities/Clothing/Head/hardsuit-helmets.yml, Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/Cybersun.yml
Изменены показатели бронирования скафандра суперсолдата киберсан
=> Supersoldier's rig armor changed

Resources/Prototypes/ADT/Entities/Clothing/Head/hardsuit-helmets.yml, Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/Cybersun.yml
Очередное изменение боссоброни
=> Configure armor after event prepare

Resources/Prototypes/ADT/Demon/Body/Parts/demon.yml, Resources/Prototypes/ADT/Moth/Body/Parts/moth.yml, Resources/Prototypes/ADT/Shark/Body/Parts/Shark.yml, Resources/Prototypes/ADT/Tajaran/Body/Parts/Tajaran.yml, Resources/Prototypes/ADT/Vulpkanin/Body/Parts/Vulpkanin.yml, Resources/Prototypes/Body/Parts/kobalt.yml
=> Fixed mover for custom races

Resources/Prototypes/Entities/Objects/Tools/tools.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/caseless_rifle.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/heavy_rifle.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/light_rifle.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/magnum.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/pistol.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/rifle.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/shotgun.yml
=> Cнова фиксим цену. Абузят даже так

Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
Возврат челюстей в инвентарь парамедика
=> Jaws of life comeback

Resources/Prototypes/Catalog/Fills/Backpacks/duffelbag.yml
усилены агенты РЗБЗЗ
Патроны изменены на зажигательные
Двустволка заменена на силовик
=> CBURN agent powerup

Content.Server/DeviceLinking/Systems/DoorSignalControlSystem.cs
=> fix door crash from corvux

Content.Server/Administration/Commands/BanCommand.cs, Content.Server/Administration/Commands/DepartmentBanCommand.cs, Content.Server/Administration/Commands/RoleBanCommand.cs, Content.Server/Administration/Managers/RoleBanManager.cs, Content.Server/Database/ServerDbBase.cs, Content.Server/Database/ServerDbManager.cs, Content.Server/Database/ServerDbPostgres.cs, Content.Server/Database/ServerDbSqlite.cs, Content.Server/Discord/Webhooks/Embed.cs, Content.Server/Discord/Webhooks/EmbedFooter.cs, Content.Server/Discord/Webhooks/WebhookPayload.cs, Content.Shared/CCVar/CCVars.cs
Добавлен вебхук для соединения банов игры и канала Discord сервера
=> Discord automated bans

Content.Client/Inventory/StrippableBoundUserInterface.cs, Resources/Prototypes/InventoryTemplates/human_inventory_template.yml
changed slot's places in stripping menu
fix size BoundUIStripping menu
=> Change stripping slots

Resources/Prototypes/Catalog/uplink_catalog.yml
=> hotfix bug

Resources/Locale/ru-RU/ADT/Narsi/narsi.ftl
=> translation fix

Resources/Prototypes/Roles/Jobs/Civilian/janitor.yml
Убран спавн инспектора у санитаров
=> janitorFix

Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
фикс шлюзов. раньше их анимация застревала на последнем кадре. Позаимствовано у corvax.
=> airlocks fix. base_structureairlocks.yml corvax openUnlitVisible: true

Resources/Maps/quadro.yml
=> fix quadro

Content.Server/Administration/Commands/DepartmentBanCommand.cs, Content.Server/Administration/Commands/RoleBanCommand.cs
Возвращение сообщений о банах в дискорд Часть 1
=> returned message from department and role bans to discord

Resources/Locale/ru-RU/ADT/Catalog/fills/items/belt.ftl, Resources/Prototypes/ADT/KD/Cargo/VectorCrate.yml, Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/OfficerBlueSheld.yml, Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/backpack.yml, Resources/Prototypes/Catalog/Fills/Items/belt.yml, Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Заменил в рюкзаке СЩ Вектор на Дрозд c резиновыми, 2 магазина резиновых, 2 магазина летала
=> Замена оружия Синего Щита (нерф)

Resources/Prototypes/ADT/Damage/ADTmodifiers.yml, Resources/Prototypes/ADT/Demon/Mobs/Species/demon.yml, Resources/Prototypes/ADT/Shark/Entities/Mobs/Species/Shark.yml, Resources/Prototypes/ADT/Tajaran/Entities/Mobs/Species/Tajaran.yml, Resources/Prototypes/ADT/Vulpkanin/Entities/Mobs/Species/Vulpkanin.yml, Resources/Prototypes/Damage/modifier_sets.yml, Resources/Prototypes/Entities/Mobs/Species/kobalt.yml
Убрал гигансткую скорость почти у всех ксено рас
Дал другие модификаторы урона (не только сопротивление урону как у унатхов)
=> Ребаланс ксеносов

Content.Shared/Damage/Systems/StaminaSystem.cs, Resources/Prototypes/Damage/types.yml, Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Добавил скафандрам ядерщиков резист к стану
Скафандр командира 60%
Скафандр джагера 60%
Скафандр элиты 50%
Скафандр оперативника 40%
=> смерть станмете

Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml
Исправление ошибки, когда было невозможно построить укрепленную стену
=> Фикс укрепленных стен

Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/telescopic_baton.yml
Убрал урон у телескопички, добавив его в стамина урон. Всё для того что бы легально избивать сотрудников!
=> небольшой ребаланс телескопички

Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Recipes/Lathes/security.yml
Добавил то что добавил кот - стандартные магазины в крафт тех фаба
=> перенёс крафты магазинов кота

Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/GorkaClothingset.yml
=> Мелкий фикс.

Content.Shared/Damage/Systems/StaminaSystem.cs, Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml, Resources/Prototypes/ADT/Catalog/uplink.yml, Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/telescopic_baton.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml, Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml, Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/pistol.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/light_rifle.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/rifle.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
Починил баг с ПКМом
чутка бафнул кастомные наборы нюкеров
чутка бафнул МК58
чутка бафнул секхуд
чутка бафнул скафы нюкеров
=> починил стамина систему

Content.Client/Players/PlayTimeTracking/JobRequirementsManager.cs, Content.Client/Preferences/UI/HumanoidProfileEditor.xaml.cs, Content.Shared/Roles/AntagPrototype.cs, Resources/Prototypes/Roles/Antags/nukeops.yml, Resources/Prototypes/Roles/Antags/traitor.yml
Предатель теперь требует 10 часов за СБ и 10 часов за мед отсек
Ядерный оперативник требует 20 часов за СБ и 20 часов за мед отсек
Ядерный медик требует 20 часов за СБ и 30 часов за мед отсек
Командир ядерных оперативников требует 20 часов за СБ, 30 часов за мед отсек и 20 часов за командование
=> роли предателей и ядерных оперативников требуют время

Resources/Maps/Shuttles/emergency_delta.yml, Resources/Prototypes/ADT/Catalog/Fills/Items/pyotr_briefcase.yml, Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/xc67.yml, Resources/Prototypes/Catalog/Bounties/bounties.yml, Resources/Prototypes/Catalog/Cargo/cargo_security.yml, Resources/Prototypes/Catalog/Cargo/cargo_vending.yml, Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Пофиксил цены из консоли наград карго, на которые ругалась проверка
Также пофиксил некоторые цены покупки в карго, на которые ругалась проверка
=> Фиксы 31.08.2023

Content.Server/GameTicking/Rules/Components/NukeopsRuleComponent.cs, Resources/Locale/ru-RU/ADT/Catalog/store/uplink.ftl, Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml, Resources/Prototypes/ADT/Catalog/uplink.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml, Resources/Prototypes/Entities/Structures/Power/chargers.yml
увеличил время на подготовку станции + 10 минут
починил сумку с оружием у АКМС и новой штурмовой винтовкой
слегка бафнул зарядку
добавил набор с 3 магазинами патрон новой винтовки для нюкеров
=> небольшой балансный патч

Content.Shared/Salvage/Fulton/FultonComponent.cs, Content.Shared/Salvage/Fulton/FultonedComponent.cs, Resources/Locale/ru-RU/ADT/Catalog/store/uplink.ftl, Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/xc67.yml, Resources/Prototypes/Catalog/Cargo/cargo_armory.yml, Resources/Prototypes/Catalog/Fills/Crates/armory.yml, Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml, Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/collector.yml
переработка фултона
переработка цен
починил скаф нюкеров (и ОБР соответственно)
=> небольшие бафы

Resources/Prototypes/Roles/Jobs/Security/detective.yml
=> вернул револьвер детективу

Resources/Prototypes/Catalog/uplink_catalog.yml
=> убрал у нюкеров возможность покупать пингвинов

Resources/Prototypes/ADT/Voice/speech_emotes.yml
Я рачела, и добавил такой файл не в ту папку. Вследствие этого, апстрим затёр его после меня.
:cl:
- add: definition of emote для гантелей и гирь
- fix: эмоции от занятия спортом с гантелями и гирями.
=> speech-emotes для athletics добавлены.

Content.IntegrationTests/Tests/PostMapInitTest.cs, Resources/Prototypes/Recipes/Lathes/security.yml
Нашел откуда началась одна из ошибок - пытаюсь поправить
Временно из теста удалил квадро. Как и саму квадро.
=> Исправление ошибок дебага

Resources/Prototypes/Recipes/Lathes/security.yml
Пофиксил дублирующие рецепты в охранном техфабе
=> фикс рецепта охранного техфаба

Resources/Prototypes/Entities/Mobs/Cyborgs/borg_chassis.yml
Изменены законы у инженерного и утилизаторского борга
Очень странно иметь законы по сохранности экипажа исходя из специализации работы именно этих боргов
=> Новые законы у двух боргов

Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml, Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
Убран странный ттс у боргов и автоматов которые режут слух
=> Скажем нет роботтсерам

Resources/Prototypes/Entities/Objects/Shields/shields.yml
здоровье щитов уменьшено до пятиста
=> фикс здоровья щитов

Resources/Prototypes/ADT/Demon/Body/Parts/demon.yml, Resources/Prototypes/ADT/Shark/Body/Parts/Shark.yml, Resources/Prototypes/ADT/Tajaran/Body/Parts/Tajaran.yml, Resources/Prototypes/ADT/Vulpkanin/Body/Parts/Vulpkanin.yml, Resources/Prototypes/Body/Parts/diona.yml, Resources/Prototypes/Body/Parts/kobalt.yml
ксеносам наконец то урезали абонемент в качалку и они перестали качать ноги
=> кто то пропустил день ног

Content.Server/Chemistry/ReagentEffects/SatiateThirst.cs, Content.Server/Medical/VomitSystem.cs, Content.Shared/CCVar/CCVars.cs, Content.Shared/Nutrition/Components/ThirstComponent.cs, Content.Shared/Nutrition/EntitySystems/ThirstSystem.cs, Resources/Prototypes/Catalog/Fills/Crates/salvage.yml, Resources/Prototypes/Entities/Markers/Spawners/Random/salvage.yml, Resources/Prototypes/Entities/Objects/Specific/syndicate.yml, Resources/Prototypes/Procedural/salvage_difficulties.yml, Resources/Prototypes/Procedural/salvage_loot.yml
Вернул ADT лут в экспы
подрезал визардский лут с экп
сделал экспы длинее на 2 минуты
они не откатываются пол года
=> Фиксы и дефиксы

Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
Предложение которое было довольно залайкано,решил ввести
=> Таксиботы стали быстрее

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml, Resources/Prototypes/Catalog/Fills/Lockers/security.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml, Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
До решения проблем с видимостью иконки у невидимок в HUD`ах СБ - они временно убраны из шкафчиков и вендоматов
у обычных СБ очков забран компонент СБ худа
=> Уменьшение числа HUD`ов у СБ

Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
- НТ решили вновь уполномочить парамедика доступом в химическую лабораторию.
=> paramedick access

Resources/Prototypes/Entities/Mobs/Player/silicon.yml
Добавил в щит спавн панель боргов с предзагружеными модулями своей специализации
=> Больше киборгов
